baseURL = "https://shaorui0.github.io/"
languageCode = "en-us"
title = "Justin Shao's Blog"
theme = "PaperMod"
publishDir = "docs"

defaultContentLanguage = "en"

[languages.en]
  languageName = "English"
  weight = 1
  contentDir = "content/en"
  title = "Justin Shao's Blog"

[languages.zh]
  languageName = "中文"
  weight = 2
  contentDir = "content/zh"

[languages.ja]
  languageName = "日本語"
  weight = 3
  contentDir = "content/ja"

[params]
  author = "Justin Shao"
  description = "Cloud Software Development Engineer's Blog"
  social = [
    { icon = "envelope", link = "mailto:sr1054461216@gmail.com" },
    { icon = "github", link = "https://github.com/shaorui0" },
    { icon = "linkedin", link = "https://www.linkedin.com/in/your-linkedin-profile" }
  ]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
